palawiki/champions/routes.py
from flask import (render_template, redirect, url_for,
                    flash, request, abort, Blueprint)
from flask_login import current_user, login_required
from palawiki import db
from palawiki.models import Champion, Pictures
from palawiki.champions.forms import (ChampionPost, PicturePost, UpdateChampion,
                            UpdatePortait)

champions = Blueprint('champions', __name__)


@champions.route("/create", methods=['POST', 'GET'])
@login_required
def newpost():
  form = ChampionPost()
  if form.validate_on_submit():
    flash('Your post has been created successfully', 'success')
    post = Champion(name=form.name.data, title=form.title.data, role=form.role.data, hp=form.hp.data,
                    speed=form.speed.data, summary=form.summary.data, content=form.content.data,
                    skill_1=form.skill_1.data, skill_2=form.skill_2.data, skill_3=form.skill_3.data,
                    skill_4=form.skill_4.data, skill_5=form.skill_5.data, portait=form.portait.data,
                    author=current_user)
    db.session.add(post)
    db.session.commit()
    return redirect(url_for('main.championslist'))
  return render_template('new_entry.html', title='New Entry', form=form, legend='Create a new entry')


@champions.route("/champions/<int:champion_id>/edit", methods=['GET', 'POST'])
@login_required
def edit(champion_id):
  post = Champion.query.get_or_404(champion_id)
  if post.author != current_user:
    abort(403)
  form = UpdateChampion()
  if form.validate_on_submit():
    post.name = form.name.data
    post.title = form.title.data
    post.role = form.role.data
    post.hp = form.hp.data
    post.speed = form.speed.data
    post.summary = form.summary.data
    post.content = form.content.data
    post.skill_1 = form.skill_1.data
    post.skill_2 = form.skill_2.data
    post.skill_3 = form.skill_3.data
    post.skill_4 = form.skill_4.data
    post.skill_5 = form.skill_5.data
    db.session.commit()
    flash('Your entry has been updated!', 'success')
    return redirect(url_for('main.full_article', champion_id=post.id))
  elif request.method == 'GET':
    form.name.data = post.name
    form.title.data = post.title
    form.role.data = post.role
    form.hp.data = post.hp
    form.speed.data = post.speed
    form.summary.data = post.summary
    form.content.data = post.content
    form.skill_1.data = post.skill_1
    form.skill_2.data = post.skill_2
    form.skill_3.data = post.skill_3
    form.skill_4.data = post.skill_4
    form.skill_5.data = post.skill_5
    return render_template('edit_entry.html', title='Update Entry', post=post, form=form, legend='Update the current entry')


@champions.route("/champions/<int:champion_id>/delete", methods=['POST'])
@login_required
def delete(champion_id):
  post = Champion.query.get_or_404(champion_id)
  if post.author != current_user:
    abort(403)
  db.session.delete(post)
  db.session.commit()
  flash('Your entry has been deleted!', 'success')
  return redirect(url_for('main.championslist'))


@champions.route("/champions/<int:champion_id>/change", methods=['GET', 'POST'])
def change_portait(champion_id):
  post = Champion.query.get_or_404(champion_id)
  form = UpdatePortait()
  if form.validate_on_submit():
    post.portait = form.portait.data
    db.session.commit()
    flash('The Portait has been updated!', 'success')
    return redirect(url_for('main.full_article', champion_id=post.id))
  elif request.method == 'GET':
    form.portait.data = post.portait
    return render_template('change_portait.html', title='Portait', post=post, form=form, legend='Change the current Portait')


@champions.route("/upload", methods=['GET', 'POST'])
@login_required
def upload_picture():
  posts = Champion.query.all()
  form = PicturePost()
  pics = Pictures.query.order_by(Pictures.champion_id)
  if form.validate_on_submit():
    flash('The Picture has been uploaded!', 'success')
    post = Pictures(img_file=form.img_file.data,
                    champion_id=form.champion_id.data, champion_name=form.champion_name.data)
    db.session.add(post)
    db.session.commit()
    return redirect(url_for('main.gallery'))
  return render_template('upload_picture.html', title='Uploading', form=form, posts=posts, pics=pics, legend="Upload a new Picture")


@champions.route("/gallery/<int:picture_id>", methods=['GET', 'POST'])
def full_picture(picture_id):
  pics = Pictures.query.get_or_404(picture_id)
  return render_template('full_picture.html', title=pics.champion_name, pics=pics)


@champions.route("/gallery/<int:picture_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_picture(picture_id):
  pics = Pictures.query.get_or_404(picture_id)
  db.session.delete(pics)
  db.session.commit()
  flash('The picture has been deleted!', 'success')
  return redirect(url_for('main.gallery'))

palawiki/main/routes.py
from flask import Blueprint, render_template, redirect, request
from palawiki.models import Champion, User, Pictures

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html', title='Home')


@main.route("/champions")
def championslist():
  page = request.args.get('page', 1, type=int)
  posts = Champion.query.order_by(
      Champion.name.asc()).paginate(page=page, per_page=3)
  return render_template('champion_list.html', title='Champions List', posts=posts)


@main.route("/champions/<int:champion_id>", methods=['GET', 'POST'])
def full_article(champion_id):
  post = Champion.query.get_or_404(champion_id)
  return render_template('full_article.html', title=post.name, post=post)


@main.route("/user/<string:username>")
def user_posts(username):
  page = request.args.get('page', 1, type=int)
  user = User.query.filter_by(username=username).first_or_404()
  posts = Champion.query.filter_by(author=user)\
      .order_by(Champion.name.asc())\
      .paginate(page=page, per_page=4)
  return render_template('user_posts.html', title='Champions List', posts=posts, user=user)


@main.route("/gallery", methods=['GET', 'POST'])
def gallery():
  pics = Pictures.query.order_by(Pictures.champion_id)
  return render_template('gallery.html', title='Gallery', pics=pics)

palawiki/users/routes.py
from flask import (render_template, redirect, url_for, 
                   flash, request, abort, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required 
from palawiki import db, bcrypt
from palawiki.models import User, Champion
from palawiki.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                            RequestResetForm, ResetPasswordForm)
from palawiki.users.utilities import send_reset_email

users = Blueprint('users', __name__)


@users.route("/user/<string:username>")
def user_posts(username):
  page = request.args.get('page', 1, type=int)
  user = User.query.filter_by(username=username).first_or_404()
  posts = Champion.query.filter_by(author=user)\
      .order_by(Champion.name.asc())\
      .paginate(page=page, per_page=4)
  return render_template('user_posts.html', title='Champions List', posts=posts, user=user)


@users.route("/register", methods=['GET', 'POST'])
def register():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = RegistrationForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(
        form.password.data).decode('utf-8')
    user = User(username=form.username.data,
                email=form.email.data, password=hashed_password)
    db.session.add(user)
    db.session.commit()
    flash(f'Account has been created! You are now able to log in.', 'success')
    return redirect(url_for('users.login'))
  return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
      login_user(user, remember=form.remember.data)
      next_page = request.args.get('next')
      return redirect(next_page) if next_page else redirect(url_for('main.home'))
    else:
      flash('Login unsuccessful. Please check email and password', 'danger')
  return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
  logout_user()
  return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
  user = User.query.get_or_404(current_user.id)
  form = UpdateAccountForm()
  if form.validate_on_submit():
    current_user.username = form.username.data
    current_user.email = form.email.data
    current_user.image_file = form.picture_link.data
    db.session.commit()
    flash('Your account info has been updated.', 'success')
    return redirect(url_for('users.account'))
  elif request.method == 'GET':
    form.username.data = current_user.username
    form.email.data = current_user.email
    form.picture_link.data = current_user.image_file
  return render_template('account.html', title='Account', form=form, user=user)


@users.route("/account/<int:user_id>", methods=['GET', 'POST'])
@login_required
def delete_account(user_id):
  user = User.query.get_or_404(user_id)
  logout_user()
  db.session.delete(user)
  db.session.commit()
  flash('The user has been deleted!', 'success')
  return redirect(url_for('main.home'))


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = RequestResetForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    send_reset_email(user)
    flash('An email has been sent to reset your password.', 'info')
    return redirect(url_for('users.login'))
  return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  user = User.verify_reset_token(token)
  if user is None:
    flash('That is an expired or invalid token', 'warning')
    return redirect(url_for('users.reset_request'))
  form = ResetPasswordForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(
        form.password.data).decode('utf-8')
    user.password = hashed_password
    db.session.commit()
    flash(f'Password has been updated! You are now able to log in.', 'success')
    return redirect(url_for('users.login'))
  return render_template('reset_token.html', title='Reset Password', form=form)

palawiki/templates/account.html
{% extends "base.html" %}
<!-- extended from -->
{% block body %}
<div class="content-section">
    <div class="d-flex justify-content-start flex_article mb-3">
        <a class="btn btn-secondary mt-2 mb-2 btn-block w-25 block_button" href="{{url_for('main.home')}}"><i class="fas fa-home"></i> Home</a>
    </div>
    <div class="media">
        <img class="account-img inner" src="{{ current_user.image_file }}">
        <div class="media-body borders">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <!-- FORM GOES HERE -->
    <form action="" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account info</legend>
            <div class="form-group">
                <!-- label -->
                {{ form.username.label(class="form-control-label") }}
                <!-- start error if -->
                {% if form.username.errors %}
                <!-- start if -->
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <!-- start for -->
                    <span>{{ error }}</span>
                    <!-- endif -->
                    {% endfor %}
                </div>
                {% else %}
                <!-- start else -->
                {{ form.username(class="form-control form-control-lg") }}
                <!-- endif -->
                {% endif %}
            </div>
            <div class="form-group">
                <!-- label -->
                {{ form.email.label(class="form-control-label") }}
                <!-- start error if -->
                {% if form.email.errors %}
                <!-- start if -->
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <!-- start for -->
                    <span>{{ error }}</span>
                    <!-- endif -->
                    {% endfor %}
                </div>
                {% else %}
                <!-- start else -->
                {{ form.email(class="form-control form-control-lg") }}
                <!-- endif -->
                {% endif %}
            </div>
            <div class="form-group">
                <!-- label -->
                {{ form.picture_link.label(class="form-control-label") }}
                <!-- start error if -->
                {% if form.picture_link.errors %}
                <!-- start if -->
                {{ form.picture_link(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.picture_link.errors %}
                    <!-- start for -->
                    <span>{{ error }}</span>
                    <!-- endif -->
                    {% endfor %}
                </div>
                {% else %}
                <!-- start else -->
                {{ form.picture_link(class="form-control form-control-lg") }}
                <!-- endif -->
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group d-flex justify-content-between flex_article">
            <button type="button" class="btn btn-danger m-1 btn-block mr-4 block_button" data-toggle="modal" data-target="#deleteModal">Delete Account <i class="fas fa-trash"></i></button>
            <!-- submit form -->
            {{ form.submit(class="btn btn-info m-1 btn-block ml-4 block_button")}}
        </div>
    </form>
    <!-- start modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete account?</h5>
                    <button id="x_symbol" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    <p class="lead">This can't be unmade, are you sure you wanna proceed?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{url_for('users.delete_account', user_id=current_user.id)}}" method="POST">
                        <input class="btn btn-danger float-right" type="submit" value="Delete account">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- endblock -->
{% endblock body %}

palawiki/templates/champion_list.html
{% extends "base.html" %}
<!-- extended from -->
{% block body %}
<!-- block start -->

<div class="d-flex justify-content-between flex_article">
    <a class="btn btn-secondary mr-4 mt-2 mb-2 btn-block block_button " href="{{url_for('main.home')}}"><i class="fas fa-home"></i> Home</a>
    <a class="btn btn-primary m-2 btn-block block_button " href="{{url_for('main.gallery')}}">Gallery <i class="fas fa-images"></i></a>
    <!-- start if -->
    {% if current_user.is_authenticated %}
    <a class=" btn btn-success ml-4 mt-2 mb-2 btn-block block_button " href="{{url_for('champions.newpost')}}">New Entry <i class="fas fa-plus-square"></i></a>
    <!-- endif -->
    {% endif %}
</div>
<div class="text-center mb-4">
    <h1>Champions List:</h1>
</div>
<!-- for starts -->
{% for post in posts.items %}
<article class="media content-section mb-4">
    <div class="d-flex justify-content-between flex_article">
        <div class="media-body">
            <div class="article-metadata d-flex">
                <figure class="img-cont mb-3">
                    <img class="article-img img-cont" src="{{ post.author.image_file }}" alt="post.author.username">
                </figure>
                <article class="mt-2">
                    <a class="mr-2" href="{{ url_for( 'users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <br/>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </article>
            </div>
            <div class="text-center">
                <h2><a class="article-title" href="{{ url_for( 'main.full_article', champion_id=post.id) }} ">{{ post.name }}</a></h2>
            </div>
            <div class="text-center">
                <img class="w-75 img-thumbnail small_pic shadow" src="{{post.portait}} " alt="{{post.name}} ">
            </div>
            <div class="article-metadata text-center">
                <h5><a class="article-title text-muted " href="{{url_for( 'main.full_article', champion_id=post.id)}} "><em>{{ post.title }}</em></a></h5>
            </div>
            <div class="article-metadata">
                <h5 class="article-content">Role:</h5>
                <ul>
                    <li>
                        <p class="article-content lead">{{ post.role }}</p>
                    </li>
                </ul>
            </div>
            <div class="article-metadata">
                <h5 class="article-content">Summary: </h5>
                <ul>
                    <li>
                        <p class="article-content lead">{{ post.summary }}</p>
                    </li>
                </ul>
            </div>
            <div class="article-metadata">
                <small class="text-muted">To check the full article, click the Champion's name</small>
            </div>
        </div>
    </div>
</article>
<!-- endfor /champions/{{ post.id }}-->
{% endfor %}
<!-- for starts -->
<div class="text-center ">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    <!-- for -->
    {% if page_num %}
    <!-- 2nd for -->
    {% if posts.page == page_num %}
    <a class="btn btn-secondary mb-4 " href="{{url_for( 'main.championslist', page=page_num)}} ">{{page_num}}</a>
    <!-- else -->
    {% else %}
    <a class="btn btn-outline-secondary mb-4 " href="{{url_for( 'main.championslist', page=page_num)}} ">{{page_num}}</a>
    <!-- endif -->
    {% endif %}
    <!-- else -->
    {% else %}
    <!-- else -->
    ...
    <!-- endif -->
    {% endif %}
    <!-- endfor -->
    {% endfor %}
</div>
<!-- end block -->
{% endblock body %}

palawiki/templates/full_article.html
{% extends "base.html" %}
<!-- extended from -->
{% block body %}
<!-- block start -->
<div class="d-flex justify-content-start flex_article">
    <a class="btn btn-secondary mb-3 btn-block w-25 block_button" href="{{url_for('main.championslist')}}"><i class="fas fa-list-alt"></i> Champions</a>
</div>

<div class="text-center mb-4">
    <h1>Full Article:</h1>
</div>

<!-- for starts -->
<article class="media content-section pl-2 pr-3 pt-2 pb-3">
    <div class="img-cont">
        <img class="float-left article-img" src="{{ post.author.image_file }}" alt="post.author.username">
    </div>
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <!-- start if -->
        {% if post.author == current_user %}
        <div class="d-flex flex_article justify-content-between article-metadata">
            <button class="btn btn-danger mt-2 mr-3 mb-2 btn-block block_button" type="button" data-toggle="modal" data-target="#deleteModal">Delete <i class="fas fa-trash"></i></button>
            <a class="btn btn-primary mb-2 mr-2 ml-2 btn-block block_button" href="{{url_for('champions.change_portait', champion_id=post.id)}}">Change Portait <i class="fas fa-camera"></i></a>
            <a class="btn btn-success mb-2 ml-3 btn-block block_button" href="{{url_for('champions.edit', champion_id=post.id)}}">Update <i class="fas fa-edit"></i></a>
        </div>
        <!-- endif -->
        {% endif %}

        <div class="centrado">
            <h2><a class="article-title" href="{{url_for('main.championslist')}}">{{ post.name }}</a></h2>
        </div>
        <div>
            <img class="w-50 float-right img-thumbnail small_pic shadow" src="{{post.portait}}" alt="{{post.name}}">
        </div>
        <div class="article-metadata centrado">
            <h5><a class="article-title text-muted" href="{{url_for('main.championslist')}}"><em>{{ post.title }}</em></a></h5>
        </div>
        <div class="article-metadata">
            <h4 class="article-content">Role:</h4>
            <ul>
                <li>
                    <p class="article-content lead">{{ post.role }}</p>
                </li>
            </ul>
        </div>
        <div class="article-metadata">
            <h4 class="article-content">HP Stats: </h4>
            <ul>
                <li>
                    <p class="article-content lead">{{ post.hp }}</p>
                </li>
            </ul>
        </div>
        <div class="article-metadata">
            <h4 class="article-content">Movement Speed: </h4>
            <ul>
                <li>
                    <p class="article-content lead">{{ post.speed }}</p>
                </li>
            </ul>
        </div>
        <div class="article-metadata">
            <h4 class="article-content">Summary: </h4>
            <ul>
                <li>
                    <p class="article-content lead">{{ post.summary }}</p>
                </li>
            </ul>
        </div>
        <div class="article-metadata">
            <h4 class="article-content">Story and Lore: </h4>
            <ul>
                <li>
                    <p class="article-content lead">{{ post.content }}</p>
                </li>
            </ul>
        </div>
        <div class="article-metadata">
            <h4 class="article-content">Abilities: </h4>
            <ul>
                <li>
                    <p class="article-content lead">{{ post.skill_1 }}</p>
                </li>
                <li>
                    <p class="article-content lead">{{ post.skill_2 }}</p>
                </li>
                <li>
                    <p class="article-content lead">{{ post.skill_3 }}</p>
                </li>
                <li>
                    <p class="article-content lead">{{ post.skill_4 }}</p>
                </li>
                <li>
                    <p class="article-content lead">{{ post.skill_5 }}</p>
                </li>
            </ul>
        </div>
        </>
    </div>
</article>
<!-- start modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Entry?</h5>
                <button id="x_symbol" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="lead">This can't be unmade, are you sure you wanna proceed?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{url_for('champions.delete', champion_id=post.id)}}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
<!-- end block -->
{% endblock body %}

palawiki/templates/gallery.html
{% extends "base.html" %}
<!-- extended from -->
{% block body %}
<div class="d-flex justify-content-between flex_article">
    <a class="btn btn-secondary mr-3 mt-2 mb-2 btn-block block_button" href="{{url_for('main.championslist')}}"><i class="fas fa-list-alt"></i> Champions</a>
    <!-- if  -->
    {% if current_user.is_authenticated %}
    <a class="btn btn-success ml-3 mt-2 mb-2 btn-block block_button" href="{{url_for('champions.upload_picture')}}">New Picture <i class="fas fa-camera"></i></a>
    <!-- endif -->
    {% endif %}
</div>
<div class="text-center d-inline">
    <h1>Champions Gallery:</h1>
</div>
<div class="alert alert-warning" role="alert">
    I don't own any of the pictures shown bellow, all credits go to their artists.
</div>

<div class="row row-cols-2">
    {% for pic in pics %}
    <div class="col-md-6 shadow inner">
        <figure class="figure round">
            <div class="text-center mt-2 mb-4">
                <figcaption class="figure-caption">{{pic.champion_name}}</figcaption>
            </div>
            <img src="{{pic.img_file}}" class="figure-img rounded w-100" alt="{{pic.champion_name}}">
            <!-- if  -->
            {% if current_user.is_authenticated %}
            <div class="d-flex justify-content-around mt-3 flex_article">
                <a class="btn btn-secondary m-1 mb-3 btn-block w-75 block_button" href="{{url_for('champions.full_picture', picture_id=pic.id)}}">Open in new tab</a>
            </div>
            <!-- endif -->
            {% endif %}
        </figure>
    </div>
    {% endfor %}
</div>
<!-- end -->
{% endblock%}

palawiki/templates/home.html
{% extends "base.html" %}
<!-- extended from -->
{% block body %}
<div class="jumbotron text-center round">
    <h1 class="display-6">Welcome to my fanmade Wiki!</h1>
    <br/>
    <div class="text-left pl-4 pr-4">
        <p class="">Well, I decided to make it as a personal (and small) project, just for fun, but also to learn and practice while doing something related to a game I like.</p>
        <p class="">And well, after a few days of coding, and a bunch of Youtube tutorials watched, this is the outcome, though it's simple and I plan on update it from time to time, making it look better and better (hopefully).</p>
    </div>
</div>
<hr>
<div class="container">
    <div class="card mb-3 shadow cards round">
        <div class="inner round">
            <img class="card-img-top img-fluid" src="https://wallpapercave.com/wp/wp1912718.jpg" alt="Card image cap">
        </div>
        <div class="card-body">
            <!-- start if -->
            {% if current_user.is_authenticated %}
            <h3 class="card-title">Help the wiki to grow!</h3>
            <p class="card-text">We're stronger together!</p>
            <div class="d-flex justify-content-between flex_article">
                <a href="{{url_for('champions.newpost')}}" class="btn btn-primary btn-block mr-4 mt-2 block_button">Add new entry <i class="fas fa-plus-square"></i></a>
                <a href="{{url_for('champions.upload_picture')}}" class="btn btn-primary btn-block mt-2 ml-4 block_button">Add new Picture <i class="fas fa-camera"></i></a>
            </div>
            <!-- else -->
            {% else %}
            <h3 class="card-title">Would like to help the wiki grow?</h3>
            <div class="mb-3">
                <p class="card-text">We're stronger together!</p>
            </div>
            <div class="d-flex justify-content-between flex_article">
                <a href="{{url_for('users.register')}}" class="btn btn-primary btn-block w-25 block_button">Register now! <i class="fas fa-user-plus"></i></a>
            </div>
            <!-- endif -->
            {% endif %}
        </div>
    </div>
    <div class="card mb-3 shadow cards round">
        <div class="inner round">
            <img class="card-img-top img-fluid" src="https://pbs.twimg.com/media/DNHWvGkW4AEcaMb.jpg" alt="Card image cap">
        </div>
        <div class="card-body">
            <h3 class="card-title">Champions list</h3>
            <p class="card-text"></p>
            <div class="d-flex justify-content-between flex_article">
                <a href="{{url_for('main.championslist')}}" class="btn btn-primary btn-block w-25 block_button">Check them out <i class="fas fa-list-alt"></i></a>
            </div>
        </div>
    </div>
    <div class="card mb-3 shadow cards round">
        <div class="inner round">
            <img class="card-img-top img-fluid" src="https://i.pinimg.com/originals/42/df/d6/42dfd6b0477a872a54ae19db8af32177.jpg" alt="Card image cap">
        </div>
        <div class="card-body">
            <h3 class="card-title">Want to see some art?</h3>
            <p class="card-text">I don't own any of the art, all the credit goes to it's respective artist.</p>
            <div class="d-flex justify-content-between flex_article">
                <a href="{{url_for('main.gallery')}}" class="btn btn-primary btn-block w-25 block_button">Check out the gallery <i class="fas fa-images"></i></a>
            </div>
        </div>
    </div>
</div>
<!-- end block -->
{% endblock body %}

palawiki/templates/reset_request.html
{% extends "base.html" %}
<!-- extended from -->
{% block body %}
<div class="content-section">
    <div class="d-flex justify-content-between flex_article">
        <a class="btn btn-secondary mt-1 mb-2 btn-block w-25 block_button" href="{{url_for('users.login')}}"><i class="fas fa-sign-in-alt"></i> Login</a>
    </div>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                <!-- label -->
                {{ form.email.label(class="form-control-label") }}
                <!-- start error if -->
                {% if form.email.errors %}
                <!-- start if -->
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <!-- start for -->
                    <span>{{ error }}</span>
                    <!-- endif -->
                    {% endfor %}
                </div>
                {% else %}
                <!-- start else -->
                {{ form.email(class="form-control form-control-lg") }}
                <!-- endif -->
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group d-flex justify-content-around flex_article">
            {{ form.submit(class="btn btn-info btn-block w-50 block_button") }}
        </div>
    </form>
</div>
{% endblock body %}